### ISSUE TITLE
Plastic pack missing UI textures for Legacy4J

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [BrandonItaly/LCE-Resources#1]
I'm trying to install this pack with the latest version of Legacy4J (1.7.2) for 1.20.6, but it seems some GUI textures are missing.
![2024-09-03_07 37 34](https://github.com/user-attachments/assets/bd53b533-542f-4175-ba22-7c8ff23ba91e)
![2024-09-03_07 38 19](https://github.com/user-attachments/assets/a0676984-ab2a-49b9-a7a2-18e258baa427)
It's not just limited to the settings, though. the backgrounds for things like the legacy edition crafting GUI is also unchanged.

Also it appears the GUI tab textures are wrong, too, although they are clearly changed by the resource pack.

**Comment by BrandonItaly** [comment]
Fixed in latest release
