### ISSUE TITLE
Natural texture pack and fantasy texture pack 1.21.3: invisible tamed wolves

### ISSUE THREAD

**Issue by konejopollo** [BrandonItaly/LCE-Resources#7]
Tamed wolves except for one variant are invisible, only collars are visible. 
Mods in use: 
-fabric
-boxlib
-debugkeybind
-entity model features
-entity texture features
-litematica
-malilib
-minihud
-modmenu
-mousetweaks
-sodium
![2024-11-02_23 28 25](https://github.com/user-attachments/assets/4db790e8-c2a8-4bfd-943c-a9beb63721a0)
![2024-11-02_23 28 48](https://github.com/user-attachments/assets/836ec1b8-62d8-48c0-8312-090f747a50bc)

**Comment by BrandonItaly** [comment]
Fixed in latest release
